config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :tips
  resources :lessons, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson_topic.rb
class LessonTopic < ApplicationRecord
  #ASSOCIATIONS
  has_many :tips 
  has_many :users, through: :tips 

  #VALIDATIONS
  validates :name, presence: true 
  validates :description, presence: true 
  validates :course_order, presence: true 
end

app/models/rating.rb
class Rating < ApplicationRecord
  #ASSOCIATIONS
  belongs_to :user 
  belongs_to :tip 

  #VALIDATIONS 
  validates :user_id, presence: true
  validates :tip_id, presence: true 
  validates :stars, presence: true 

end

app/models/tip.rb
class Tip < ApplicationRecord
  #ASSOCIATIONS
  belongs_to :user 
  belongs_to :lesson_topic 

  has_many :ratings 
  has_many :users, through: :ratings 

  #VALIDATIONS 
  validates :user_id, presence: true 
  validates :lesson_topic_id, presence: true 
  validates :name, presence: true 
  validates :description, presence: true 
  validates :resource_link, presence: true 

  #SCOPE
  default_scope -> {order(created_at: :desc)}
end

app/models/user.rb
class User < ApplicationRecord
    #ASSOCIATIONS 
    has_many :tips, dependent: :destroy 
    has_many :lesson_topics, through: :tips 
    has_many :ratings, dependent: :destroy
    has_many :lesson_topics, through: :ratings 
    
    
    
    #VALIDATIONS
    before_save { self.email = email.downcase }  #this appears unnecessary, however, as the email address is being indexed, the index may be case sensitive.  To not worry about this the email address is standardized prior to going in the db. 
    validates :name, presence: true, length: {maximum: 255}
    EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255},
     format: { with: EMAIL_REGEX}, uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, presence: true,  length: {minimum: 6}, allow_nil: true 


    #TESTING 
    def User.digest(string)  #needed to set up fixtures/users.yml Uses low 
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private 
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in to view this page."
      redirect_to login_url
    end 
  end 

  def set_user
    @user = User.find(params[:id])
  end 

  def correct_user 
    set_user
    redirect_to root_url unless @user == current_user
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new 
  end 

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
        log_in(user)
        redirect_back_or user 
    else 
      flash.now[:danger] = "Invalid email/password combination."
      render 'new'
    end 
  end 

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
require 'pry'
class StaticPagesController < ApplicationController
  def home 
     if logged_in? 
       @user = current_user 
       @tips = current_user.tips
     end 
  end

  def about 
  end 
end

app/controllers/tips_controller.rb
require 'pry'

class TipsController < ApplicationController
before_action :logged_in_user, only:[ :create, :destroy]
before_action :set_tip, only: [:destroy, :edit, :show]
  def new
    @tip = Tip.new 
    @options = LessonTopic.all.map{|l| [l.name, l.id]}.unshift(['', -1])  
  end 

  def create 
    @tip = current_user.tips.build(tip_params)
    if @tip.save
      flash[:success] = "Thanks! Your tip has been added."
      redirect_to root_path
    else
    
      @options = LessonTopic.all.map{|l| [l.name, l.id]}.unshift(['', -1])    
      @user = current_user
        render 'tips/new'
     
    end
  end 

  def edit 
    if current_user != @tip.user 
      redirect_to root_path 
    end 
  end 

  def update 
  end 

  def show 
  end  

  def destroy 
    if current_user != @tip.user 
      redirect_to root_path 
    else 
      @tip.destroy
    end 
  end 

  def index 
  end 

private 
  def tip_params
    params.require(:tip).permit(:name, :description, :lesson_topic_id, :resource_link)
  end

  def set_tip
    @tip = Tip.find(params[:id])
  end 


end

app/controllers/users_controller.rb
require 'pry'
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :logged_in_user, only:[:edit, :update, :index]
  before_action :correct_user,   only: [:edit, :update]
  def new
    @user = User.new 
  end

  def show #Show User data and the tips that they have provided 
    if @user.tips
    @tips = @user.tips
    else  
      @tips = []
    end

  end 

  def create
    @user = User.new(user_params)
    if @user.save 
      log_in(@user)
      flash[:success] = "welcome to BURNorSPURN"
      redirect_to @user 
    else 
      render 'new'
    end 
  end 

  def edit 
  end 

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end 
  end 

  def index 
    @users = User.all 
  end 

  def destroy 
  end 



private 

  def user_params
    params.require(:user).permit(:name, :email, :password,
                               :password_confirmation, :has_graduated)
  end


end 

app/helpers/application_helper.rb
module ApplicationHelper
    #Returns the full titl on a per-page basis 
    def full_title(page_title = '')
        base_title = "IN_APP_HELPER"
        if page_title.empty?
          base_title
        else
          page_title
        end
      end
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
      session[:user_id] = user.id
    end 
    
    def current_user
      if session[:user_id]
        @current_user ||= User.find_by(id: session[:user_id])  # Same as @current_user = @current_user || User.find_by(id: session[:user_id])
      end 
    end

    def logged_in?
       !current_user.nil?
    end 
    
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end

    def log_in_as(user)
      session[:user_id] = user.id
    end

    #The below two methods are there to enable 'friendly-forwarding'.  If a user is prompted to log in when trying to access a page that requires login, then after providing credentials, the user experience is improved if the user is redirected to the original site they were trying to access.  
    def redirect_back_or(default)
      redirect_to(session[:forwarding_url] || default)
      session.delete(:forwarding_url)
    end

    def store_location
      session[:forwarding_url] = request.original_url if request.get?
    end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <nav>
    <ul>
      <li><%= link_to "Home",   root_path %></li>
      <li><%= link_to "About", about_path %></li>
   
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
      <div class="container" id="header">
        <%= link_to "// LearnHELP", root_path, id: "logo" %>
        <nav>
        
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Lessons", lessons_path %></li>
            <% if logged_in?%>
              <%= render 'layouts/logged_in'%>
            <% else %>
            <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_logged_in.html.erb
<li> <%= link_to "Users", users_path%></li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Account <b class="caret"></b>
</a>
<ul class="dropdown-menu">
    
    <li><%= link_to "Profile", current_user %></li>
    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
    <li class="divider"></li>
    <li>
    <%= link_to "Log out", logout_path, method: :delete %>
    </li>
</ul>
</li>

app/views/layouts/_rails_default.html.erb
 <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <title><%= full_title(yield(:title)) %></title>
    <%= render '/layouts/rails_default'%>
    <%= render 'shared/shim'%>
  </head>
    <%= render '/layouts/header' %>
  <body>
    <div class="container">
      <%= render 'shared/flash'%>
      <%= yield %>
      <%= render '/layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
    
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/shared/_shim.html.erb
 <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/static_pages/_not_logged_in.html.erb
<% provide(:title, "Home") %>



<div class="center jumbotron">
    <h1>Welcome to LearnHELP</h1>

    <h2>
      A place for students to provide targeted tips to others feeling the pain of learning something new. 
    </h2>
<button class = "standard-input-button">
    <%=link_to "Sign up now!", signup_path%>
</button><br><br>


<a href="/auth/facebook" class="btn btn-sm btn-social btn-facebook">
  <span class="fa fa-facebook"></span>
  Sign in with Facebook
</a>

<a href="/auth/github" class="btn btn-sm btn-social btn-github">
  <span class="fa fa-github"></span>
  Sign in with Github
</a>


  </div>
   <h3 id='plug'>What is the Flatiron School?  Who are you people? Check it out!     
  <%= link_to image_tag("learn.png", alt: "Learn Link"),
              'https://flatironschool.com/' %></h3>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home")%>
<% if logged_in?%>
  <%= render 'users/user_with_his_tips' %>
<%else %>
  <%= render 'not_logged_in'%>
<% end %>

app/views/tips/_tip.html.erb
<li id="tip-<%= tip.id %>">
  <span class="user"><%= link_to tip.user.name, tip.user %></span>
  <span class="content"><%= tip.description %></span>
  <span class="content"><%= link_to "Edit", edit_tip_path(tip) %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(tip.created_at) %> ago.
  </span>
</li>

app/views/tips/_tip_form.html.erb
<%= form_for(@tip, html: {class: 'form-group'}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">

    <%= f.text_field :name, placeholder: "Add your title..." %>
    <%= f.text_field :resource_link, placeholder: "Add your link..." %>
    <%= f.text_area :description, placeholder: "Add a description..." %>
    <%= f.select(:lesson_topic_id, @options) %>

  </div>
  <%= f.submit "Post", class: "standard-input-button" %>
<% end %>

app/views/tips/new.html.erb
<% provide(:title, 'Add Tip') %>

<%= render 'tip_form'%>

app/views/tips/show.html.erb
<% provide(:title, @tip.name) %>

<ol class="tips">
  <%= render @tip %>
</ol>

app/views/users/_form.html.erb
<div class='row'>
  <div class="col-md-6 col-md-offset-3">
     <%= form_for(@user) do |f|%>
       <%= render '/shared/error_messages', object: f.object%>
       <%= f.label :name %>
       <%= f.text_field :name %><br>
       
       <%= f.label :email %>
       <%= f.email_field :email %><br>
       
       <%= f.label :password %>
       <%= f.password_field :password %><br>

       <%= f.label :password_confirmation, "Confirmation" %>
       <%= f.password_field :password_confirmation %><br>

    
       <div>
       <p>Have you graduated from the course?</p>
       
        <%= f.radio_button :has_graduated, 1 %> 
        <%= label :has_graduated, 'Yes' %><br>
        <%= f.radio_button :has_graduated, 0 %> 
        <%= label :has_graduated, 'No' %>
      </div>
      <br>


       <%= f.submit yield(:button_text), class: "btn btn-primary" %>
     <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<li ><%= link_to(user.name, user)%><span>Joined <%= user.created_at.strftime('%B %Y')%></span></li>

app/views/users/_user_with_his_tips.html.erb
 <aside class="col-md-6">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
      <h1>
      <%= @user.email%></h1>
    </section>
  </aside>
   <div class="col-md-8">
    <% if @tips.any? %>
      <h3>Your Tips: (<%= @tips.count %>)</h3>
      <ol class="tips">
        <%= render @tips %>
      </ol>
    <% end %>
  </div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<% provide(:button_text, 'Save changes') %>

<h1>Update your profile</h1>
 
<%= render 'form'%>

app/views/users/index.html.erb
<% provide(:title, 'User Index')%>

<h1>User Index</h1>

<ul class="users">
  <% @users.each do |user|%>
    <%= render @users%>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Our gnraly picture ratings are more accurate if you sign up!</h1>

<%= render 'form'%>

app/views/users/show.html.erb
<% provide(:title, 'Home') %>

<%= render 'user_with_his_tips' %>